name: Recent GitHub Activity

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with recent activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        with:
          COMMIT_MSG: "Updated README with recent GitHub activity"
          MAX_LINES: 10
